# Network
MODEL_USE: mgfn
ARCH: {
    enc: [SA, SA, SA, SA, FFN, FFN, FFN, FFN, SA, FFN, FFN, FFN],
    dec: [GAoA, GAoA, FFN, FFN, GAoA, FFN, RSAoA, GAoA, FFN, GAoA, RSAoA, FFN, RSAoA, SAoA, FFN, RSAoA, GAoA, FFN]
}
HIDDEN_SIZE: 1024
REL_HBASE: 128
REL_SIZE: 64
MULTI_HEAD: 8
DROPOUT_R: 0.1
FLAT_MLP_SIZE: 1024
FLAT_GLIMPSES: 1
FLAT_OUT_SIZE: 2048


BATCH_SIZE: 64
LR_BASE: 0.00005
LR_DECAY_R: 0.2
LR_DECAY_LIST: [10, 11]
WARMUP_EPOCH: 3
MAX_EPOCH: 12
GRAD_NORM_CLIP: 1.0
GRAD_ACCU_STEPS: 1
LOSS_FUNC: bce
LOSS_REDUCTION: sum
OPT: Adam
OPT_PARAMS: {betas: '(0.9, 0.98)', eps: '1e-9'}
