# Network
MODEL_USE: mmnasnet
ARCH: {
#    enc: [SA, SA, SA, SA, FFN, FFN, FFN, FFN, SA, FFN, FFN, FFN],
#    dec: [GA, GA, FFN, FFN, GA, FFN, RSA, GA, FFN, GA, RSA, FFN, RSA, SA, FFN, RSA, GA, FFN]
#    enc: [ SA, SA, SA, SA, FFN, FFN, FFN, FFN ,FFN, FFN, FFN, FFN ],
#    dec: [ RSA, GA, FFN, RSA, GA, FFN, RSA, GA, FFN, RSA, GA, FFN ,RSA, GA, FFN, FFN]
    enc: [ SA, SA, SA, SA, FFN, FFN, FFN, FFN ,FFN, FFN, FFN, FFN ],
    dec: [ SA, GA, FFN, SA, GA, FFN, SA, GA, FFN, SA, GA, FFN ,SA, GA, FFN, FFN ]
}
HIDDEN_SIZE: 1024
REL_HBASE: 128
REL_SIZE: 64
MULTI_HEAD: 8
DROPOUT_R: 0.1
FLAT_MLP_SIZE: 1024
FLAT_GLIMPSES: 1
FLAT_OUT_SIZE: 2048
#USE_BBOX_FEAT: True
#USE_AUX_FEAT: True

# Execution
BATCH_SIZE: 64
LR_BASE: 0.00005  # 5e-5 for train+val+vg->test
LR_DECAY_R: 0.2
LR_DECAY_LIST: [8, 10]
WARMUP_EPOCH: 3
MAX_EPOCH: 11
GRAD_NORM_CLIP: 1.0
GRAD_ACCU_STEPS: 1
LOSS_FUNC: ce
LOSS_REDUCTION: sum
OPT: Adam
OPT_PARAMS: {betas: '(0.9, 0.98)', eps: '1e-9'}
